### ISSUE TITLE
Research the Existing Tools

### ISSUE THREAD

**Issue by VincentLa** [VincentLa/ucsf-mh-conflicts-of-interest#3]
**Goal**
Research Existing Geocoding tools to see how we can provide as input an address and return:

- Latitude
- Longitude
- Census Tract
- Census Block Group
- Census Block

**Things to Consider**
1. What is the Python Package we can use?
2. Does it require an API key?
3. If it requires an API key, how much does it cost? Can we create an organization account?

**Comment by VincentLa14** [comment]
Existing Python Package: https://github.com/fitnr/censusgeocode

Looks like No Special API Key needed? But The Census might rate limit us?
