### ISSUE TITLE
Take all addresses in Table, Geocode, add as new columns, and write as new table to DB.

### ISSUE THREAD

**Issue by VincentLa14** [VincentLa/ucsf-mh-conflicts-of-interest#5]

**Comment by benjaminbang987** [comment]
According to https://pypi.org/project/censusgeocode/, batch encoding exists - but the files have to be in 1000s with columns as `unique id, street address, state, city, zip code`.
(example: https://github.com/fitnr/censusgeocode/blob/master/tests/fixtures/batch.csv)

**Comment by VincentLa14** [comment]
#9
